# Generated by Django 5.1.5 on 2025-02-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tasktype",
        ),
        migrations.AddField(
            model_name="task",
            name="task_types",
            field=models.ManyToManyField(
                related_name="tasks", to="task_manager.tasktype"
            ),
        ),
    ]
