# Generated by Django 5.1.5 on 2025-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasktype',
        ),
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.ManyToManyField(related_name='tasktypes', to='task_manager.tasktype'),
        ),
    ]
