# Generated by Django 5.1.5 on 2025-02-11 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_remove_task_tasktype_task_task_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="task_manager.position",
            ),
        ),
    ]
